---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-monitor
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: dns-monitor
  namespace: kube-system
  labels:
    app: dns-monitor
spec:
  selector:
    app: dns-monitor
  ports:
  - name: metrics
    port: 80
    protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: dns-monitor
  namespace: kube-system
  labels:
    app: dns-monitor
    version: v0.1.4
spec:
  replicas: 1
  selector:
    app: dns-monitor
    version: v0.1.4
  template:
    metadata:
      labels:
        app: dns-monitor
        version: v0.1.4
      annotations:
        homeworld.mit.edu/unsupported-fetch-info: aci
    spec:
      serviceAccountName: dns-monitor
      containers:
      - name: kube-dns-monitor
        image: homeworld.private/dns-monitor:0.1.6
        command:
        - /usr/bin/dns-monitor
        - kubernetes.default.svc.{{INTERNAL_DOMAIN}}={{SERVIP_API}}
        - kube-dns.kube-system.svc.{{INTERNAL_DOMAIN}}={{SERVIP_DNS}}
        resources:
          limits:
            memory: 150Mi
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 80
          name: metrics
          protocol: TCP
