apiVersion: v1
kind: Service
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeDNS"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: {{SERVIP_DNS}}
  ports:
  - name: dns
    port: 53
    protocol: UDP
  - name: dns-tcp
    port: 53
    protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-v20
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    version: v20
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 3
  selector:
    k8s-app: kube-dns
    version: v20
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        version: v20
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
        homeworld.mit.edu/unsupported-fetch-info: aci
    spec:
      containers:
      - name: kubedns
        image: homeworld.private/kube-dns-main:1.14.8-3
        args:
        - /usr/bin/kube-dns
        - --domain={{INTERNAL_DOMAIN}}.
        - --dns-port=10053
        - -v=2
        env:
        - name: PROMETHEUS_PORT
          value: "10055"
        ports:
        - containerPort: 10053
          name: dns-local
          protocol: UDP
        - containerPort: 10053
          name: dns-tcp-local
          protocol: TCP
        - containerPort: 10055
          name: metrics
          protocol: TCP
      - name: dnsmasq
        image: homeworld.private/dnsmasq-nanny:1.14.8-4
        args:
        - /usr/bin/dnsmasq-nanny
        - -v=2
        - -logtostderr
        - -configDir=/etc/k8s/dns/dnsmasq-nanny
        - -restartDnsmasq=true
        - --
        - -k
        - --cache-size=1000
        - --no-negcache
        - --log-facility=-
        - --server=/{{INTERNAL_DOMAIN}}/127.0.0.1#10053
        - --server=/in-addr.arpa/127.0.0.1#10053
        - --server=/ip6.arpa/127.0.0.1#10053
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
      - name: sidecar
        image: homeworld.private/kube-dns-sidecar:1.14.8-3
        args:
        - /usr/bin/sidecar
        - --v=2
        - --logtostderr
        - --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.{{INTERNAL_DOMAIN}},5,A
        - --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.{{INTERNAL_DOMAIN}},5,A
        ports:
        - containerPort: 10054
          name: metrics
          protocol: TCP
      dnsPolicy: Default  # don't use cluster DNS.
